create database 
customer_shopping_behavior;

select*
from dbo.customer;

select count(*) 
from dbo.customer;

--total revenue generated by male vs  female customers

select gender, sum(purchase_amount) as revenue 
from dbo.customer
group by gender;

--customers those used discount but still spent more than the average purchase amount

select customer_id, purchase_amount
from dbo.customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from dbo.customer);

--top 5 products with the highest average review rating

select top 5 item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from dbo.customer
group by item_purchased
order by avg(review_rating) desc;

-- comparing average spend and total revenue 
-- between subscribers and non subscribers.

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend,
sum(purchase_amount) as total_revenue
from dbo.customer
group by subscription_status
order by total_revenue, average_spend desc;

-- 5 products that have the highest percentage of purchase
-- with discounts applied 

select  top 5 item_purchased,
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from dbo.customer
group by item_purchased
order by discount_rate desc;

-- segment customers into categories based on their total 
--number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from dbo.customer
)

select customer_segment, count(*) as "Number_of_Customers"
from customer_type
group by customer_segment
order by Number_of_Customers desc;

--top 3  most purchased products within each category.

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from dbo.customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- are customers who are repeat buyers also likely to subscribe

select subscription_status,
count(customer_id) as repeat_buyers
from dbo.customer
where previous_purchases > 5
group by subscription_status;

-- revenue contribution of each age group

select age_group,
sum(purchase_amount) as total_revenue
from dbo.customer
group by age_group
order by total_revenue desc;










